name: my_assistance
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  # Utils
  go_router: 14.8.1
  get: 4.7.2
  cached_network_image: 3.4.1
  flutter_svg: 2.0.17
  smooth_page_indicator: ^1.2.1
  path_provider: ^2.1.5
  get_it: ^8.0.3

  # translation
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  flutter_slidable: ^4.0.0

  #offline
  hive_flutter: 1.1.0
  hive: ^2.2.3
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/animations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Medium.ttf


